apiVersion: v1
kind: Service
metadata:
  name: blocking-http-proxy
spec:
  selector:
    app: blocking-http-proxy
  ports:
    - name: proxy
      protocol: TCP
      port: 8080
      targetPort: 8080
